<?php
/**
 * @var \App\View\Renderer\DummyRenderer $this
 * @var \Woda\MezzioModule\User\App\Login\LoginForm $form
 * @var string $token
 */
$form->get('csrf')->setValue($token);
?>
<section class="form-login">
    <?= $this->partial('user::partial/header', ['title' => 'Login']) ?>
    <?= $this->form($form) ?>
    <div>
        <ul>
            <li><a href="<?= $this->url('register') ?>">Register</a></li>
            <li><a href="<?= $this->url('password-reset') ?>">Lost Password?</a></li>
            <li><a href="<?= $this->url('home') ?>">Home</a></li>
        </ul>
    </div>
</section>
