<?php
/**
 * @var DummyRenderer $this
 * @var RegisterForm $form
 * @var string $token
 */

use App\View\Renderer\DummyRenderer;
use Woda\MezzioModule\User\App\Register\RegisterForm;

?>
<section class="form-register">
    <?= $this->partial('user::partial/header', ['title' => 'Registration']) ?>
    <?= $this->form($form) ?>
    <div>
        <ul>
            <li><a href="<?= $this->url('login') ?>">Login</a></li>
            <li><a href="<?= $this->url('password-reset') ?>">Lost Password?</a></li>
            <li><a href="<?= $this->url('home') ?>">Home</a></li>
        </ul>
    </div>
</section>
