<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <link rel="shortcut icon" href="https://getlaminas.org/ico/favicon.ico"/>
    <?= $this->headTitle('Admin')->setSeparator(' - ')->setAutoEscape(false) ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
</head>
<body class="app">
<header class="app-header">
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse"
                        aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <!-- Brand -->
                <a class="navbar-brand" href="<?= $this->url('admin.dashboard') ?>">
                    Admin
                </a>
            </div>
            <!-- Links -->
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a href="https://docs.mezzio.dev/mezzio" target="_blank" class="nav-link">
                            <i class="fa fa-book"></i> Docs
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="https://github.com/mezzio/mezzio" target="_blank" class="nav-link">
                            <i class="fa fa-wrench"></i> Contribute
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="<?= $this->url('api.ping') ?>" class="nav-link">
                            Ping Test
                        </a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>

<div class="app-content">
    <main class="container">
        <?php if ($flashes = $this->flash()) : ?>
            <ul>
                <?php foreach ($flashes as $message) : ?>
                    <li><?= $message ?></li>
                <?php endforeach; ?>
            </ul>
        <?php endif; ?>
        <?= $this->content ?>
    </main>
</div>

<footer class="app-footer">
    <div class="container">
        <hr/>
        <p>
            &copy; 2005 - <?= date('Y') ?> by Laminas Technologies Ltd. All rights reserved.
        </p>
    </div>
</footer>

<?= $this->inlineScript() ?>
</body>
</html>
