<?php
/**
 * @var $this \Core\View\DummyRenderer
 */

?>
<?php
$this->headLink()
    ->prependStylesheet('https://use.fontawesome.com/releases/v5.0.6/css/all.css')
    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css');
$this->inlineScript()
    ->prependFile('https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js')
    ->prependFile('https://code.jquery.com/jquery-3.3.1.min.js');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="https://getlaminas.org/ico/favicon.ico" />
    <?=$this->headTitle('App')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <style>
        body { padding-top: 70px; }
        .app { min-height: 100vh; }
        .app-footer { padding-bottom: 1em; }
        .api-tools-green, h2 a { color: #68b604; }
    </style>
</head>
<body class="app">

    <div class="app-content">
        <main class="container">
            <?php if ($flashes = $this->flash()) :?>
                <ul>
                    <?php foreach($flashes as $message) : ?>
                        <li><?= $message ?></li>
                    <?php endforeach; ?>
                </ul>
            <?php endif; ?>
            <?= $this->content ?>
        </main>
    </div>

    <?=$this->inlineScript()?>
</body>
</html>
