<?php
/**
 * @var $this \Core\View\DummyRenderer
 */
?>
<?php $this->headTitle('Home'); ?>

<div class="jumbotron">
    <h1>Welcome to <span class="api-tools-green">mezzio-skeleton</span></h1>
</div>

<?php if ($this->user !== null) : ?>
    <a class="btn btn-primary" href="<?= $this->url('backend.dashboard') ?>">Go to backend</a>
<?php else : ?>
    <a class="btn btn-primary" href="<?= $this->url('register') ?>">Register</a> |
    <a class="btn btn-primary" href="<?= $this->url('login') ?>">Login</a>
<?php endif ?>
