<?php
/**
 * @var $this \Laminas\View\Renderer\PhpRenderer
 */
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <?= $this->headTitle('App')->setSeparator(' | ')->setAutoEscape(false) ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
</head>
<body>
<?php if ($flashes = $this->flash()) : ?>
    <ul>
        <?php foreach ($flashes as $message) : ?>
            <li><?= $message ?></li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
<?= $this->content ?>
</body>
</html>

